### PR TITLE
README changes & fix for anonbeat/guayadeque#114

### PR DESCRIPTION
**Pull request by openmonk**
Renamed README to .md, corrected formatting, added fast build instructions & ubuntu 20.04 dependencies (fix for anonbeat/guayadeque#114)

### CODE REVIEW

**Comment by anonbeat** [comment]
There is no libindicator dependency. There is no support for this library and will not be used.

**Comment by openmonk** [comment]
Sorry, I was not sure - cmake gave me an error, but the compilation worked fine.
I'll do another pull request without it.

**Comment by openmonk** [comment]
JFYI, the error I'm getting without it:
--   No package 'indicate' found
 libindicate library not found! No sound menu support!!

**Comment by anonbeat** [comment]
Its right as libindicate support was dropped long ago.

**Pull request closed without merging**
